### ISSUE TITLE
Alias for identity

### ISSUE THREAD

**Issue by raine** [raine/ramda-cli#2]
`identity` gets typed a lot, and I already have a keyboard macro `\id → identity` for it.

Thinking if it should be aliased to something like `I`, as it used to be in ramda.

**Comment by davidchambers** [comment]
`I` makes sense to me.

**Comment by vendethiel** [comment]
shift+i is two keys, and `id` also is two keys.

**Comment by raine** [comment]
I settled on `id` because

```
$ ... | R I
```

looks funny
