### ISSUE TITLE
Collision with R programming language

### ISSUE THREAD

**Issue by lbeschastny** [raine/ramda-cli#3]
`R` is already reserved by [R programming language CLI][1].

  [1]: https://en.wikipedia.org/wiki/R_(programming_language)

**Comment by jeroenjanssens** [comment]
I suggest renaming it to `ramda` (all lowercase).

**Comment by jeroenjanssens** [comment]
I see in package.json that the binary is actually called `ramda` and that both `ramda` and `R` are mapped to this.
