### ISSUE TITLE
Question: how to make destructing of object?

### ISSUE THREAD

**Issue by lapanoid** [raine/ramda-cli#6]
Hi, thanks for your awesome lib. I am wondering if there any way to do destructuring on some object with it. For example:
`cat channels_list.json | R keys` - gives me
```
[
"ok",
"channels"
]
```
And I want to get `channels`
`cat channels_list.json | R '(x => x.channels)'` - does not work

**Comment by raine** [comment]
Hi Sergey, can you give an example of `channels_list.json`?

**Comment by lapanoid** [comment]
Ahh thanks, you right just missed --js flag!
